name:                hasskell-lib
version:             0.1.0.0
github:              martinjonsson01/hasskell
license:             BSD-3-Clause
author:              Martin Jonsson
maintainer:          hasskell@jmartin.se
copyright:           2025 Martin Jonsson

dependencies:
- base >= 4.7 && < 5
- aeson >= 2.2.3 && < 2.3
- deriving-aeson >= 0.2.10 && < 0.3
- aeson-pretty >= 0.8.10 && < 1.0
- text >= 2.0 && <= 2.0
- bytestring >= 0.12 && <= 1.0
- utf8-string >= 1.0 && <= 2.0
- filepath >= 1.5 && <= 2.0
- text-metrics >= 0.3 && < 1.0
- heap >= 1 && < 2
- containers >= 0.6.8 && < 0.8
- websockets >= 0.13 && < 0.14
- mtl >= 2.3.1 && < 3
- bytestring >= 0.12.2.0 && < 0.13
- stm >= 2.5 && < 3
- time >= 1.12 && < 2
- pretty-show >= 1.10 && < 2
- can-i-haz >= 0.3.1.1 && < 1
- effectful >= 2.6 && < 3
- effectful-core >= 2.6 && < 3
- effectful-th >= 1.0.0.3 && < 2
- effectful-plugin >= 2.0.0.1 && < 3
- singletons >= 3 && < 4
- singletons-th >= 3 && < 4
- utility-ht >= 0.0.17 && < 0.1
- diagnose >= 2.5.1 && < 3
- prettyprinter >= 1.7 && < 2
- prettyprinter-ansi-terminal >= 1.1 && < 2


default-extensions:
- StandaloneKindSignatures
- TypeOperators
- DerivingStrategies
- DeriveAnyClass 
- TypeApplications
- OverloadedStrings
- ImportQualifiedPost
- DerivingVia
- BangPatterns
- BinaryLiterals
- ConstraintKinds
- DataKinds
- DefaultSignatures
- DeriveDataTypeable
- DeriveFoldable
- DeriveFunctor
- DeriveGeneric
- DeriveTraversable
- DoAndIfThenElse
- EmptyDataDecls
- ExistentialQuantification
- FlexibleContexts
- FlexibleInstances
- FunctionalDependencies
- GADTs
- GeneralizedNewtypeDeriving
- InstanceSigs
- KindSignatures
- LambdaCase
- MultiParamTypeClasses
- MultiWayIf
- NamedFieldPuns
- OverloadedStrings
- PartialTypeSignatures
- PatternGuards
- PolyKinds
- RankNTypes
- RecordWildCards
- ScopedTypeVariables
- StandaloneDeriving
- TupleSections
- TypeFamilies
- TypeSynonymInstances
- ViewPatterns

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wincomplete-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints
- -fplugin=Effectful.Plugin

library:
  source-dirs: src

tests:
  hasskell-lib-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hasskell-lib
    - sydtest >= 0.20 && < 1
    - sydtest-hedgehog >= 0.4 && < 1
    - hedgehog >= 1.5 && < 2
    build-tools:
      sydtest-discover:sydtest-discover
